# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  
    branches:
    - dev
    - main
    - feature/*
  pull_request:
    branches:
    - dev
    - main
    - feature/*
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Install OpenModelica
      uses: THM-MoTE/setup-openmodelica@v1
      with:
        version: 1.17.0
    - name: Install Modelica standard library
      run: sudo apt-get install omlib-modelica-3.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew test -i
    - name: Upload project to SonarQube
      run: >
        ./gradlew sonarqube
        -Dsonar.projectKey=MopeSWTP-SS21
        -Dsonar.host.url=https://scm.thm.de/sonar
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
