# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
  
    branches:
    - dev
    - main
    - feature/*
  pull_request:
    branches:
    - dev
    - main
    - feature/*
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    #- name: Install OpenModelica
    #  uses: THM-MoTE/setup-openmodelica@v1
    #  with:
    #    version: 1.17.0
    #- name: Install Modelica standard library
    #  run: sudo apt-get install omlib-modelica-3.0
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Test with Gradle
    #  run: ./gradlew test -i
    - name: Build with Gradle
      run: ./gradlew build -x test
    - name: Add version from build.gradle to output
      id: version
      run: echo "::set-output name=version::$(./gradlew getVersion -q)"
    - name: Print Version
      run: echo ${{ steps.version.outputs.version }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #Provided by GithubActions
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release v${{ steps.version.outputs.version }}
        body: |
          Changes in this Release
          - TEST
        draft: false
        prerelease: true

